// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.2
// LVGL version: 8.3.6
// Project name: ATD35_S3_Internet_Radio

#ifndef _ATD35_S3_INTERNET_RADIO_UI_H
#define _ATD35_S3_INTERNET_RADIO_UI_H

#ifdef __cplusplus
extern "C" {
#endif

    #include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"
// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
extern lv_obj_t *ui_Screen1;
extern lv_obj_t *ui_Panel4;
extern lv_obj_t *ui_cool93;
extern lv_obj_t *ui_Label2;
extern lv_obj_t *ui_green_wave;
extern lv_obj_t *ui_Label1;
extern lv_obj_t *ui_great_93_fm;
extern lv_obj_t *ui_Label3;
extern lv_obj_t *ui_efm;
extern lv_obj_t *ui_Label4;
extern lv_obj_t *ui_Panel1;
extern lv_obj_t *ui_Panel3;
extern lv_obj_t *ui_Image2;
extern lv_obj_t *ui_volume;
extern lv_obj_t *ui_Image3;
extern lv_obj_t *ui_play_stop_btn;
extern lv_obj_t *ui_Panel8;
extern lv_obj_t *ui_Image4;
extern lv_obj_t *ui____initial_actions0;

LV_IMG_DECLARE( ui_img_bg_png);   // assets\BG.png
LV_IMG_DECLARE( ui_img_kvdhawt62s_png);   // assets\KvDHAwT62s.png
LV_IMG_DECLARE( ui_img_green_png);   // assets\green.png
LV_IMG_DECLARE( ui_img_agtuevydc9_png);   // assets\AgtUEVyDC9.png
LV_IMG_DECLARE( ui_img_efm_png);   // assets\EFM.png
LV_IMG_DECLARE( ui_img_71751729);   // assets\volume-down.png
LV_IMG_DECLARE( ui_img_1897292250);   // assets\volume-up.png
LV_IMG_DECLARE( ui_img_play_png);   // assets\play.png
LV_IMG_DECLARE( ui_img_stop_png);   // assets\stop.png
LV_IMG_DECLARE( ui_img_933478393);   // assets\Artron - 2 - 450x.png



void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
